In [241]:
import math as mt
import scipy as sc
import numpy as np

In [242]:
def generatePascalLine(n):
    return sc.linalg.pascal(n, kind = 'lower')[-1]

def createMask(line):
    simplifiedMask = np.outer(line, line)
    maskSum = np.sum(simplifiedMask)
    realMask = (1 / maskSum) * simplifiedMask

    return simplifiedMask, realMask, maskSum

def calculateStandardDeviation(n):
    return mt.sqrt((n - 1) / 2)

In [243]:
sizes = [3, 5, 7]

for size in sizes:
    pascalLine = generatePascalLine(size)
    simplifiedMask, realMask, maskSum = createMask(pascalLine)
    standardDeviation = calculateStandardDeviation(size)

    print(f'Tamanho: {size}\n')
    print(f'Desvio Padrão: {standardDeviation}')
    print(f'Multiplicador: 1 / {maskSum} ou {1 / maskSum}')
    print(f'Máscara (sem multiplicador):\n{simplifiedMask}')
    print(f'Máscara (com multiplicador):\n{realMask} \n')

Tamanho: 3

Desvio Padrão: 1.0
Multiplicador: 1 / 16 ou 0.0625
Máscara (sem multiplicador):
[[1 2 1]
 [2 4 2]
 [1 2 1]]
Máscara (com multiplicador):
[[0.0625 0.125  0.0625]
 [0.125  0.25   0.125 ]
 [0.0625 0.125  0.0625]] 

Tamanho: 5

Desvio Padrão: 1.4142135623730951
Multiplicador: 1 / 256 ou 0.00390625
Máscara (sem multiplicador):
[[ 1  4  6  4  1]
 [ 4 16 24 16  4]
 [ 6 24 36 24  6]
 [ 4 16 24 16  4]
 [ 1  4  6  4  1]]
Máscara (com multiplicador):
[[0.00390625 0.015625   0.0234375  0.015625   0.00390625]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.0234375  0.09375    0.140625   0.09375    0.0234375 ]
 [0.015625   0.0625     0.09375    0.0625     0.015625  ]
 [0.00390625 0.015625   0.0234375  0.015625   0.00390625]] 

Tamanho: 7

Desvio Padrão: 1.7320508075688772
Multiplicador: 1 / 4096 ou 0.000244140625
Máscara (sem multiplicador):
[[  1   6  15  20  15   6   1]
 [  6  36  90 120  90  36   6]
 [ 15  90 225 300 225  90  15]
 [ 20 120 300 400 300 120  20]
 [ 15  90 